package arbol;

import javax.swing.ImageIcon;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Arbol extends javax.swing.JFrame {
    DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Raiz");//entre comillas va el nombre de la carpeta principal
    DefaultTreeModel modeloTree = new DefaultTreeModel(raiz);
    public Arbol() {
        cargarDatos();
        initComponents();
    }
    
    //agregar mas subcarpetas a raiz
    private void cargarDatos(){
    DefaultMutableTreeNode colores = new DefaultMutableTreeNode("Colores");
    DefaultMutableTreeNode rojo = new DefaultMutableTreeNode("Rojo");
    DefaultMutableTreeNode azul = new DefaultMutableTreeNode("Azul");
    DefaultMutableTreeNode amarillo = new DefaultMutableTreeNode("Amarillo");
    DefaultMutableTreeNode deportes = new DefaultMutableTreeNode("Deportes");
    DefaultMutableTreeNode futbol = new DefaultMutableTreeNode("Futbol");
    DefaultMutableTreeNode tennis = new DefaultMutableTreeNode("Tennis");
    DefaultMutableTreeNode basquet = new DefaultMutableTreeNode("Basquet");
    DefaultMutableTreeNode animales = new DefaultMutableTreeNode("Animales");
    DefaultMutableTreeNode lobo = new DefaultMutableTreeNode("Lobo");
    DefaultMutableTreeNode zorro = new DefaultMutableTreeNode("Zorro");
    DefaultMutableTreeNode murcielago = new DefaultMutableTreeNode("Murcielago");
    
    raiz.add(colores);
    raiz.add(deportes);
    raiz.add(animales);
    
    colores.add(rojo);
    colores.add(azul);
    colores.add(amarillo);
    deportes.add(futbol);
    deportes.add(tennis);
    deportes.add(basquet);
    animales.add(lobo);
    animales.add(zorro);
    animales.add(murcielago);
    }
    
    private void ev(DefaultMutableTreeNode x){
        if (x.toString().equals("Rojo")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/rojo.jpg")));
        }else if (x.toString().equals("Azul")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/azul.jpg")));
        }else if (x.toString().equals("Amarillo")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/amarillo.jpg")));
        }else if (x.toString().equals("Futbol")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/fb.jpg")));
        }else if (x.toString().equals("Tennis")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/tenis.jpg")));
        }else if (x.toString().equals("Basquet")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/basquet.jpg")));
        }else if (x.toString().equals("Lobo")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/lobo.jpg")));
        }else if (x.toString().equals("Zorro")) {
            img.setIcon(new ImageIcon(getClass().getResource("/img/zorro.jpg")));
        }else {
            img.setIcon(new ImageIcon(getClass().getResource("/img/mclg.jpg")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arbol.setModel(modeloTree);
        TreeSelectionListener oyente = new TreeSelectionListener(){
            @Override
            public void valueChanged(TreeSelectionEvent e){
                DefaultMutableTreeNode selec = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
                ev(selec);
            }
        };

        arbol.getSelectionModel().addTreeSelectionListener(oyente);
        jScrollPane1.setViewportView(arbol);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
