# -*- coding: utf-8 -*-
"""06 - Funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrJc1I67LdkGQUfyE0e9NjoI-uHUUTyU
"""

def chequearSensor(sensor, umbral):
  if sensor > umbral:
    print("ALARMA!")
  else:
    print("Temperatura OK.")

temperatura1 = 100
temperatura2 = 50

chequearSensor(temperatura1, 110)

import math

math.pi

def CalcularAreaCirculo(radio):
  areaCirculo = math.pi * (radio**2)
  print("El area del circulo es", areaCirculo)

CalcularAreaCirculo(10)

